apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: tvgafq1yx-go 
  janus-idp.io/tekton: tvgafq1yx-go
  backstage.io/kubernetes-id: tvgafq1yx-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: tvgafq1yx-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml