apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: tvgafq1yx-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tvgafq1yx-go 
  name: tvgafq1yx-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: tvgafq1yx-go 
